name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with: 
          node-version: 16.8.0
          
      - name: Installing dependencies
        run: |
          npm install
          npm install -g @angular/cli

      - name: Building the project
        run: |
          ng build
